// Code generated by goctl. DO NOT EDIT.
package types

type UserDetail struct {
	Id         int64  `json:"id"`
	Name       string `json:"name"`
	Age        string `json:"age"`
	Genger     string `json:"genger"`
	Phone      string `json:"phone"`
	Address    string `json:"address"`
	CreateTime int64  `json:"createTime"`
}

type GetUserReq struct {
	Id int64 `path:"id"`
}

type GetUserResp struct {
	UserInfo UserDetail `json:"userInfo"`
}
