// Code generated by goctl. DO NOT EDIT.
package types

type UserBaseInfo struct {
	UserName     string `json:"userName"`
	NickName     string `json:"nickName"`
	Number       string `json:"number"`
	Avatar       string `json:"avatar,optional"`
	Email        string `json:"email,optional"`
	Phone        string `json:"phone,optional"`
	Address      string `json:"address,optional"`
	Position     string `json:"position,optional"`
	Introduction string `json:"introduction,optional"`
	Status       string `json:"status,optional"`
	Source       string `json:"source,optional"`
	Age          int    `json:"age,optional"`
	DeptCode     string `json:"deptCode,optional"`
	DeptName     string `json:"deptName,optional"`
	ManagerCode  string `json:"managerCode,optional"`
	ManagerName  string `json:"managerName,optional"`
	UserDn       string `json:"userDn,optional"`
}

type UserDetail struct {
	Id       int64 `json:"id"`
	CreateAt int64 `json:"createAt,optional"`
	UserBaseInfo
}

type GetUserReq struct {
	Id int64 `path:"id"`
}

type GetUserResp struct {
	UserDetail
}

type CreateUserReq struct {
	UserBaseInfo
}

type CreateUserResp struct {
	Id int64 `json:"id"`
}

type ListUserReq struct {
	ListReq
}

type ListUserResp struct {
	ListResp
	Users []UserDetail `json:"list"`
}

type DeleteUserReq struct {
	Id int64 `path:"id"`
}

type DeleteUserResp struct {
	Id int64 `json:"id"`
}

type UpdateUserReq struct {
	Id int64 `path:"id"`
	UserBaseInfo
}

type UpdateUserResp struct {
	Id int64 `json:"id"`
}

type PatchUserReq struct {
	Id int64 `path:"id"`
	UserBaseInfo
}

type PatchUserResp struct {
	Id int64 `json:"id"`
}

type ListReq struct {
	Search   string `form:"search,optional"`
	Page     int64  `form:"page,optional,default=1"`
	PageSize int64  `form:"pageSize,optional,default=10"`
}

type ListResp struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"pageSize"`
	Total    int64 `json:"total"`
}

type RoleInfo struct {
	Name string `json:"name"`
	Desc string `json:"desc"`
}

type RoleDetail struct {
	Id       int64 `json:"id"`
	CreateAt int64 `json:"createAt"`
	RoleInfo
}

type CreateRoleReq struct {
	RoleInfo
}

type CreateRoleResp struct {
	Id int64 `json:"id"`
}

type DeleteRoleReq struct {
	Id int64 `path:"id"`
}

type DeleteRoleResp struct {
	Id int64 `json:"id"`
}

type UpdateRoleReq struct {
	Id int64 `path:"id"`
	RoleInfo
}

type UpdateRoleResp struct {
	Id int64 `json:"id"`
}

type PatchRoleReq struct {
	Id int64 `path:"id"`
	RoleInfo
}

type PatchRoleResp struct {
	Id int64 `json:"id"`
}

type GetRoleReq struct {
	Id int64 `path:"id"`
}

type GetRoleResp struct {
	RoleDetail
}

type ListRoleReq struct {
	ListReq
}

type ListRoleResp struct {
	ListResp
	Roles []RoleDetail `json:"list"`
}

type ListUserRolesReq struct {
	ListReq
}

type RoleUserBase struct {
	UserId int64 `json:"userId"`
	RoleId int64 `json:"roleId"`
}

type RoleUserDetail struct {
	Id       int64  `json:"id"`
	UserName string `json:"userName"`
	RoleName string `json:"roleName"`
	CreateAt int64  `json:"createAt"`
	RoleUserBase
}

type ListUserRolesResp struct {
	ListResp
	RoleUsers []RoleUserDetail `json:"list"`
}

type AddRoleForUserReq struct {
	UserId []int64 `json:"userId"`
	RoleId int64   `path:"roleId"`
}

type AddRoleForUserResp struct {
	Id int64 `json:"id"`
}

type RemoveRoleForUserReq struct {
	UserId []int64 `json:"userId"`
	RoleId int64   `path:"roleId"`
}

type RemoveRoleForUserResp struct {
}

type PermInfo struct {
	Resource string `json:"resource"`
	Perm     string `json:"perm"`
	Desc     string `json:"desc"`
}

type PermDetail struct {
	Id       int64 `json:"id"`
	CreateAt int64 `json:"createAt"`
	PermInfo
}

type CreatePermReq struct {
	PermInfo
}

type CreatePermResp struct {
	Id int64 `json:"id"`
}

type DeletePermReq struct {
	Id int64 `path:"id"`
}

type DeletePermResp struct {
	Id int64 `json:"id"`
}

type UpdatePermReq struct {
	Id int64 `path:"id"`
	PermInfo
}

type UpdatePermResp struct {
	Id int64 `json:"id"`
}

type PatchPermReq struct {
	Id int64 `path:"id"`
	PermInfo
}

type PatchPermResp struct {
	Id int64 `json:"id"`
}

type GetPermReq struct {
	Id int64 `path:"id"`
}

type GetPermResp struct {
	PermDetail
}

type ListPermReq struct {
	ListReq
}

type ListPermResp struct {
	ListResp
	Perms []PermDetail `json:"list"`
}

type StrategyInfo struct {
	Subject     string `json:"subject"`
	SubjectType string `json:"subjectType"`
	Resource    string `json:"resource"`
	Perm        string `json:"perm"`
}

type StrategyDetail struct {
	Id int64 `json:"id"`
	StrategyInfo
	SubjectName     string `json:"subjectName"`
	SubjectTypeName string `json:"subjectTypeName"`
	ResourceName    string `json:"resourceName"`
	PermName        string `json:"permName"`
	CreateAt        int64  `json:"createAt"`
}

type CreateStrategyReq struct {
	StrategyInfo
}

type CreateStrategyResp struct {
	Id int64 `json:"id"`
}

type DeleteStrategyReq struct {
	Id int64 `path:"id"`
}

type DeleteStrategyResp struct {
	Id int64 `json:"id"`
}

type UpdateStrategyReq struct {
	Id int64 `path:"id"`
	StrategyInfo
}

type UpdateStrategyResp struct {
	Id int64 `json:"id"`
}

type PatchStrategyReq struct {
	Id int64 `path:"id"`
	StrategyInfo
}

type PatchStrategyResp struct {
	Id int64 `json:"id"`
}

type GetStrategyReq struct {
	Id int64 `path:"id"`
}

type GetStrategyResp struct {
	StrategyDetail
}

type ListStrategyReq struct {
	ListReq
}

type ListStrategyResp struct {
	ListResp
	Strategys []StrategyDetail `json:"list"`
}

type UserRoleInfo struct {
	UserId int64 `json:"userId"`
	RoleId int64 `json:"roleId"`
}

type UserRoleDetail struct {
	Id       int64 `json:"id"`
	CreateAt int64 `json:"createAt"`
	UserRoleInfo
}

type CreateUserRoleReq struct {
	UserRoleInfo
}

type CreateUserRoleResp struct {
	Id int64 `json:"id"`
}

type DeleteUserRoleReq struct {
	Id int64 `path:"id"`
}

type DeleteUserRoleResp struct {
	Id int64 `json:"id"`
}

type UpdateUserRoleReq struct {
	Id int64 `path:"id"`
	UserRoleInfo
}

type UpdateUserRoleResp struct {
	Id int64 `json:"id"`
}

type PatchUserRoleReq struct {
	Id int64 `path:"id"`
	UserRoleInfo
}

type PatchUserRoleResp struct {
	Id int64 `json:"id"`
}

type GetUserRoleReq struct {
	Id int64 `path:"id"`
}

type GetUserRoleResp struct {
	UserRoleDetail
}

type ListUserRoleReq struct {
	ListReq
}

type ListUserRoleResp struct {
	ListResp
	UserRoles []UserRoleDetail `json:"list"`
}

type WeComLoginReq struct {
	Code string `json:"code"`
}

type WeComLoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type LoginReq struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshToken string `json:"refreshToken"`
}

type LogoutReq struct {
}

type LogoutResp struct {
}

type RegisterReq struct {
	UserName string `json:"userName"`
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Id         int64  `json:"id"`
	UserName   string `json:"userName"`
	GenderCode int64  `json:"GenderCode"`
	Phone      string `json:"phone"`
}

type RefreshTokenReq struct {
}

type RefreshTokenResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type MenuInfo struct {
	AuthName string `json:"authName"`
	Path     string `json:"path"`
	Order    int64  `json:"order"`
	ParentId int64  `json:"parentId"`
}

type MenuDetail struct {
	Id int64 `json:"id"`
	MenuInfo
	Children []MenuDetail `json:"children"`
	CreateAt int64        `json:"createAt"`
}

type ListMenuReq struct {
}

type ListMenuResp struct {
	Menus []MenuDetail `json:"list"`
}
