// Code generated by goctl. DO NOT EDIT.
package types

type UserBaseInfo struct {
	Number      string `json:"number"`
	Name        string `json:"name"`
	Age         int    `json:"age,optional"`
	GenderCode  int64  `json:"genderCode,optional"`
	Phone       string `json:"phone,optional"`
	Email       string `json:"email,optional"`
	DeptCode    string `json:"deptCode,optional"`
	DeptName    string `json:"deptName,optional"`
	ManagerCode string `json:"managerCode,optional"`
	ManagerName string `json:"managerName,optional"`
}

type UserDetail struct {
	Id         int64  `json:"id"`
	Genger     string `json:"genger,optional"`
	CreateTime int64  `json:"createTime,optional"`
	UserBaseInfo
}

type GetUserReq struct {
	Id int64 `path:"id"`
}

type GetUserResp struct {
	UserDetail
}

type CreateUserReq struct {
	UserBaseInfo
}

type CreateUserResp struct {
	Id int64 `json:"id"`
}

type ListUserReq struct {
	ListReq
}

type ListUserResp struct {
	ListResp
	Users []UserDetail `json:"list"`
}

type DeleteUserReq struct {
	Id int64 `path:"id"`
}

type DeleteUserResp struct {
	Id int64 `json:"id"`
}

type UpdateUserReq struct {
	Id int64 `path:"id"`
	UserBaseInfo
}

type UpdateUserResp struct {
	Id int64 `json:"id"`
}

type PatchUserReq struct {
	Id int64 `path:"id"`
	UserBaseInfo
}

type PatchUserResp struct {
	Id int64 `json:"id"`
}

type ListReq struct {
	Page     int64 `json:"page,optioanl,default=1"`
	PageSize int64 `json:"pageSize,optional,default=10"`
}

type ListResp struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"pageSize"`
	Total    int64 `json:"total"`
}

type RoleInfo struct {
	Name string `json:"name"`
	Desc string `json:"desc"`
}

type RoleDetail struct {
	Id         int64 `json:"id"`
	CreateTime int64 `json:"createTime"`
	RoleInfo
}

type CreateRoleReq struct {
	RoleInfo
}

type CreateRoleResp struct {
	Id int64 `json:"id"`
}

type DeleteRoleReq struct {
	Id int64 `json:"id"`
}

type DeleteRoleResp struct {
	Id int64 `json:"id"`
}

type UpdateRoleReq struct {
	Id int64 `json:"id"`
	RoleInfo
}

type UpdateRoleResp struct {
	Id int64 `json:"id"`
}

type PatchRoleReq struct {
	Id int64 `json:"id"`
	RoleInfo
}

type PatchRoleResp struct {
	Id int64 `json:"id"`
}

type GetRoleReq struct {
	Id int64 `json:"id"`
}

type GetRoleResp struct {
	RoleDetail
}

type ListRoleReq struct {
	ListReq
}

type ListRoleResp struct {
	ListResp
	Roles []RoleDetail `json:"list"`
}
