// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	role "user/api/internal/handler/role"
	user "user/api/internal/handler/user"
	"user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/:id",
				Handler: user.GetUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user",
				Handler: user.CreateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user",
				Handler: user.ListUserHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/user/:id",
				Handler: user.DeleteUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/user/:id",
				Handler: user.UpdateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPatch,
				Path:    "/user/:id",
				Handler: user.PatchUserHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/role/:id",
				Handler: role.GetRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/role",
				Handler: role.CreateRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/role",
				Handler: role.ListRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/role/:id",
				Handler: role.DeleteRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/role/:id",
				Handler: role.UpdateRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodPatch,
				Path:    "/role/:id",
				Handler: role.PatchRoleHandler(serverCtx),
			},
		},
	)
}
