// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package userservice

import (
	"context"

	"github.com/super667/user/user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddRoleForUserReq     = user.AddRoleForUserReq
	AddRoleForUserResp    = user.AddRoleForUserResp
	AuthenticateReq       = user.AuthenticateReq
	AuthenticateResp      = user.AuthenticateResp
	BlackListTokenReq     = user.BlackListTokenReq
	BlackListTokenResp    = user.BlackListTokenResp
	CreatePermReq         = user.CreatePermReq
	CreatePermResp        = user.CreatePermResp
	CreateRoleReq         = user.CreateRoleReq
	CreateRoleResp        = user.CreateRoleResp
	CreateStrategyReq     = user.CreateStrategyReq
	CreateStrategyResp    = user.CreateStrategyResp
	CreateUserReq         = user.CreateUserReq
	CreateUserResp        = user.CreateUserResp
	CreateUserRoleReq     = user.CreateUserRoleReq
	CreateUserRoleResp    = user.CreateUserRoleResp
	DeletePermReq         = user.DeletePermReq
	DeletePermResp        = user.DeletePermResp
	DeleteRoleReq         = user.DeleteRoleReq
	DeleteRoleResp        = user.DeleteRoleResp
	DeleteStrategyReq     = user.DeleteStrategyReq
	DeleteStrategyResp    = user.DeleteStrategyResp
	DeleteUserReq         = user.DeleteUserReq
	DeleteUserResp        = user.DeleteUserResp
	DeleteUserRoleReq     = user.DeleteUserRoleReq
	DeleteUserRoleResp    = user.DeleteUserRoleResp
	GetPermByIdReq        = user.GetPermByIdReq
	GetPermByIdResp       = user.GetPermByIdResp
	GetRoleByIdReq        = user.GetRoleByIdReq
	GetRoleByIdResp       = user.GetRoleByIdResp
	GetStrategyByIdReq    = user.GetStrategyByIdReq
	GetStrategyByIdResp   = user.GetStrategyByIdResp
	GetUserByIdReq        = user.GetUserByIdReq
	GetUserByIdResp       = user.GetUserByIdResp
	GetUserByNameReq      = user.GetUserByNameReq
	GetUserByNameResp     = user.GetUserByNameResp
	GetUserByNumberReq    = user.GetUserByNumberReq
	GetUserByNumberResp   = user.GetUserByNumberResp
	GetUserRoleByIdReq    = user.GetUserRoleByIdReq
	GetUserRoleByIdResp   = user.GetUserRoleByIdResp
	ListAllRoleUsersReq   = user.ListAllRoleUsersReq
	ListAllRoleUsersResp  = user.ListAllRoleUsersResp
	ListPermReq           = user.ListPermReq
	ListPermResp          = user.ListPermResp
	ListRoleForUserReq    = user.ListRoleForUserReq
	ListRoleForUserResp   = user.ListRoleForUserResp
	ListRoleReq           = user.ListRoleReq
	ListRoleResp          = user.ListRoleResp
	ListStrategyReq       = user.ListStrategyReq
	ListStrategyResp      = user.ListStrategyResp
	ListUserReq           = user.ListUserReq
	ListUserResp          = user.ListUserResp
	ListUserRoleReq       = user.ListUserRoleReq
	ListUserRoleResp      = user.ListUserRoleResp
	LoginReq              = user.LoginReq
	LoginResp             = user.LoginResp
	LogoutReq             = user.LogoutReq
	LogoutResp            = user.LogoutResp
	PatchPermReq          = user.PatchPermReq
	PatchPermResp         = user.PatchPermResp
	PatchRoleReq          = user.PatchRoleReq
	PatchRoleResp         = user.PatchRoleResp
	PatchStrategyReq      = user.PatchStrategyReq
	PatchStrategyResp     = user.PatchStrategyResp
	PatchUserReq          = user.PatchUserReq
	PatchUserResp         = user.PatchUserResp
	PatchUserRoleReq      = user.PatchUserRoleReq
	PatchUserRoleResp     = user.PatchUserRoleResp
	PermDetail            = user.PermDetail
	PermInfo              = user.PermInfo
	RefreshTokenReq       = user.RefreshTokenReq
	RefreshTokenResp      = user.RefreshTokenResp
	RegisterReq           = user.RegisterReq
	RegisterResp          = user.RegisterResp
	RemoveRoleForUserReq  = user.RemoveRoleForUserReq
	RemoveRoleForUserResp = user.RemoveRoleForUserResp
	RoleDetail            = user.RoleDetail
	RoleInfo              = user.RoleInfo
	RoleUserDetail        = user.RoleUserDetail
	RoleUserInfo          = user.RoleUserInfo
	StrategyDetail        = user.StrategyDetail
	StrategyInfo          = user.StrategyInfo
	SyncOpenLdapUsersReq  = user.SyncOpenLdapUsersReq
	SyncOpenLdapUsersResp = user.SyncOpenLdapUsersResp
	UpdatePermReq         = user.UpdatePermReq
	UpdatePermResp        = user.UpdatePermResp
	UpdateRoleForUserReq  = user.UpdateRoleForUserReq
	UpdateRoleForUserResp = user.UpdateRoleForUserResp
	UpdateRoleReq         = user.UpdateRoleReq
	UpdateRoleResp        = user.UpdateRoleResp
	UpdateStrategyReq     = user.UpdateStrategyReq
	UpdateStrategyResp    = user.UpdateStrategyResp
	UpdateUserReq         = user.UpdateUserReq
	UpdateUserResp        = user.UpdateUserResp
	UpdateUserRoleReq     = user.UpdateUserRoleReq
	UpdateUserRoleResp    = user.UpdateUserRoleResp
	UserDetail            = user.UserDetail
	UserInfo              = user.UserInfo
	UserRoleDetail        = user.UserRoleDetail
	UserRoleInfo          = user.UserRoleInfo

	UserService interface {
		GetUserById(ctx context.Context, in *GetUserByIdReq, opts ...grpc.CallOption) (*GetUserByIdResp, error)
		GetUserByNumber(ctx context.Context, in *GetUserByNumberReq, opts ...grpc.CallOption) (*GetUserByNumberResp, error)
		GetUserByName(ctx context.Context, in *GetUserByNameReq, opts ...grpc.CallOption) (*GetUserByNameResp, error)
		CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error)
		DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserResp, error)
		UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UpdateUserResp, error)
		PatchUser(ctx context.Context, in *PatchUserReq, opts ...grpc.CallOption) (*PatchUserResp, error)
		ListUser(ctx context.Context, in *ListUserReq, opts ...grpc.CallOption) (*ListUserResp, error)
		SyncOpenLdapUsers(ctx context.Context, in *SyncOpenLdapUsersReq, opts ...grpc.CallOption) (*SyncOpenLdapUsersResp, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

func (m *defaultUserService) GetUserById(ctx context.Context, in *GetUserByIdReq, opts ...grpc.CallOption) (*GetUserByIdResp, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.GetUserById(ctx, in, opts...)
}

func (m *defaultUserService) GetUserByNumber(ctx context.Context, in *GetUserByNumberReq, opts ...grpc.CallOption) (*GetUserByNumberResp, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.GetUserByNumber(ctx, in, opts...)
}

func (m *defaultUserService) GetUserByName(ctx context.Context, in *GetUserByNameReq, opts ...grpc.CallOption) (*GetUserByNameResp, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.GetUserByName(ctx, in, opts...)
}

func (m *defaultUserService) CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.CreateUser(ctx, in, opts...)
}

func (m *defaultUserService) DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserResp, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.DeleteUser(ctx, in, opts...)
}

func (m *defaultUserService) UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UpdateUserResp, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.UpdateUser(ctx, in, opts...)
}

func (m *defaultUserService) PatchUser(ctx context.Context, in *PatchUserReq, opts ...grpc.CallOption) (*PatchUserResp, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.PatchUser(ctx, in, opts...)
}

func (m *defaultUserService) ListUser(ctx context.Context, in *ListUserReq, opts ...grpc.CallOption) (*ListUserResp, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.ListUser(ctx, in, opts...)
}

func (m *defaultUserService) SyncOpenLdapUsers(ctx context.Context, in *SyncOpenLdapUsersReq, opts ...grpc.CallOption) (*SyncOpenLdapUsersResp, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.SyncOpenLdapUsers(ctx, in, opts...)
}
